---
ip: '10.10.10.101'

provision_script: 'scripts/bootstrap.sh'

system_synced_folder:
  local: scripts
  remote: /home/vagrant/scripts

app_synced_folder:
  local: ~/Sites/timeorg-blog
  remote: /home/vagrant/timeorg-blog

memory: 1024
cpu: 1
